apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-ipam
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["create","update","get", "list", "delete","watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-ipam
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: global-ipam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: global-ipam
subjects:
  - kind: ServiceAccount
    name: global-ipam
    namespace: kube-system